
--Creamos las tablas en el orden correspondiente
CREATE TABLE CONCE_CIUDAD(
NOMBRE VARCHAR2(10) PRIMARY KEY,
NHABITANTES NUMBER(10));

CREATE TABLE CONCE_MARCA(
NOMBRE VARCHAR2(10) PRIMARY KEY,
CIUDAD VARCHAR2(10) NOT NULL CONSTRAINT FK_CIUD_MARC REFERENCES CONCE_CIUDAD);

CREATE TABLE CONCE_COCHE(
CODIGO VARCHAR2(8) PRIMARY KEY,
NOMBRE VARCHAR2(15),
MARCA VARCHAR2(10) NOT NULL CONSTRAINT FK_COCH_MARC REFERENCES CONCE_MARCA);

CREATE TABLE CONCE_CONCESIONARIO(
CIF NUMBER(8) PRIMARY KEY,
NOMBRE VARCHAR2(20),
CIUDAD VARCHAR2(10) NOT NULL CONSTRAINT FK_CONC_CIU REFERENCES CONCE_CIUDAD);

CREATE TABLE CONCE_CLIENTE(
IDCLI NUMBER(8) PRIMARY KEY,
NOMBRE VARCHAR2(12),
APELLIDO VARCHAR2(15),
CIUDAD VARCHAR2(10) NOT NULL CONSTRAINT FK_CLI_CIU REFERENCES CONCE_CIUDAD);

CREATE TABLE CONCE_VENTAS(
CONCESIONARIO NUMBER(8) CONSTRAINT FK_VEN_CON REFERENCES CONCE_CONCESIONARIO,
CLIENTE NUMBER(8) CONSTRAINT FK_VEN_CLI REFERENCES CONCE_CLIENTE,
COCHE VARCHAR2(8) CONSTRAINT FK_VEN_COCH REFERENCES CONCE_COCHE,
COLOR VARCHAR2(9),
FECHA DATE,
CONSTRAINT PK_VENTAS PRIMARY KEY (CONCESIONARIO,CLIENTE,COCHE));

CREATE TABLE CONCE_DISTRIBUCION(
CONCESIONARIO NUMBER(8) CONSTRAINT FK_DIS_CON REFERENCES CONCE_CONCESIONARIO,
COCHE VARCHAR2(8) CONSTRAINT FK_DIS_COCH REFERENCES CONCE_COCHE,
CANTIDAD NUMBER(3),
CONSTRAINT PK_DISTRIB PRIMARY KEY (CONCESIONARIO,COCHE));


ALTER TABLE CONCE_COCHE ADD PRECIO_BASE NUMBER(7,2);
ALTER TABLE CONCE_VENTAS ADD PRECIO_VENTA number(7,2);

/*OTROS TIPOS DE RESTRICCIONES QUE SE PODRÍAN DEFINIR*/
/*QUE LA CANTIDAD DE COCHES EN DISTRIBUCIÓN NO PUEDA SER NEGATIVA*/
ALTER TABLE CONCE_DISTRIBUCION ADD CHECK (CANTIDAD>0);

--Borramos las tablas usando la cláusula cascade constraint
--SIN CASCADE CONSTRAINT ESTE ES EL ORDEN CORRECTO. SE EVALUARÁ EL ORDEN CORRECTO.
/*DROP TABLE CONCE_DISTRIBUCION CASCADE CONSTRAINTS;
DROP TABLE CONCE_VENTAS CASCADE CONSTRAINTS;
DROP TABLE CONCE_CLIENTE CASCADE CONSTRAINTS;
DROP TABLE CONCE_CONCESIONARIO CASCADE CONSTRAINTS;
DROP TABLE CONCE_COCHE CASCADE CONSTRAINTS;
DROP TABLE CONCE_MARCA CASCADE CONSTRAINTS;
DROP TABLE CONCE_CIUDAD CASCADE CONSTRAINTS;*/
