CREATE TABLE LISTAS_PAIS(
	NOMBRE VARCHAR2(50) PRIMARY KEY
);

CREATE TABLE LISTAS_ESTADO_PROVINCIA(
    NOMBRE VARCHAR2(50),
    NOM_PAIS VARCHAR2(50) REFERENCES LISTAS_PAIS,
    CONSTRAINT PK_ESTADO_PROV PRIMARY KEY (NOMBRE, NOM_PAIS)
);

CREATE TABLE LISTAS_CIUDAD(
    NOMBRE VARCHAR2(50),
    NOM_ESTADO_PROV VARCHAR2(50),
    NOM_PAIS VARCHAR2(50),
    CONSTRAINT PK_CIUDAD PRIMARY KEY (NOMBRE, NOM_ESTADO_PROV, NOM_PAIS),
    CONSTRAINT FK_CIUDAD_ESTADO FOREIGN KEY (NOM_ESTADO_PROV, NOM_PAIS) REFERENCES LISTAS_ESTADO_PROVINCIA
);
/*La ciudad ya se relaciona con la provincia y el pais*/
CREATE TABLE LISTAS_ARTISTA(
    COD NUMBER(4) PRIMARY KEY, 
	nombreArtistico VARCHAR2(50) UNIQUE,
    NOM_CIUDAD VARCHAR2(50),
    NOM_ESTADO_PROV VARCHAR2(50),
    NOM_PAIS VARCHAR2(50),
    CONSTRAINT FK_ARTISTA FOREIGN KEY (NOM_CIUDAD, NOM_ESTADO_PROV, NOM_PAIS) REFERENCES LISTAS_CIUDAD
);

CREATE TABLE LISTAS_GRUPO(
    COD NUMBER(4) PRIMARY KEY, 
    FCREACION DATE NOT NULL,
    FDISOLUCION DATE,
    FOREIGN KEY(COD) REFERENCES LISTAS_ARTISTA
);

CREATE TABLE LISTAS_ARTISTAIND(
    COD NUMBER(4) PRIMARY KEY, 
    nombreReal VARCHAR2(100) UNIQUE not null,
    FNAC DATE not null,
    FMUERTE DATE,
    FOREIGN KEY(COD) REFERENCES LISTAS_ARTISTA
);

CREATE TABLE LISTAS_GENERO(
    COD NUMBER(4) PRIMARY KEY, 
	NOMBRE VARCHAR2(50) UNIQUE
);

CREATE TABLE LISTAS_CANCION(
    COD NUMBER(4) PRIMARY KEY,
	TITULO VARCHAR2(50) NOT NULL,
    ANYO NUMBER(4),
    COD_ARTISTA NUMBER(4) NOT NULL,
    FOREIGN KEY(COD_ARTISTA) REFERENCES LISTAS_ARTISTA
);

CREATE TABLE LISTAS_GENERO_CANCION(
    COD_CANCION NUMBER(4),
    COD_GENERO NUMBER(4),
    PRIMARY KEY(COD_CANCION, COD_GENERO),
    FOREIGN KEY(COD_CANCION) REFERENCES LISTAS_CANCION,
    FOREIGN KEY(COD_GENERO) REFERENCES LISTAS_GENERO
);

CREATE TABLE LISTAS_LISTA(
    COD NUMBER(4) PRIMARY KEY,
	NOMBRE VARCHAR2(100) NOT NULL,
    ANYO NUMBER(4) NOT NULL,
    FUENTE VARCHAR2(120),
    AUTOR VARCHAR2(50)
);

/*posicion debe formar parte de la clave primaria (o poner restriccion de unica junto con lista y cancion), porque si no podrían haber posiciones repetCODas en una misma lista para diferentes canciones*/
CREATE TABLE LISTAS_POSICION_LISTA(
    COD_CANCION NUMBER(4),
    COD_LISTA NUMBER(4),
    POSICION NUMBER(4) NOT NULL,
    PRIMARY KEY(COD_CANCION, COD_LISTA),
    FOREIGN KEY(COD_CANCION) REFERENCES LISTAS_CANCION,
    FOREIGN KEY(COD_LISTA) REFERENCES LISTAS_LISTA
);

ALTER TABLE LISTAS_ARTISTAIND ADD CONSTRAINT MORIRDESPUES CHECK (FMUERTE>FNAC);
ALTER TABLE LISTAS_GRUPO ADD CONSTRAINT DISOLVERDESPUES CHECK (FDISOLUCION>FCREACION);
ALTER TABLE LISTAS_POSICION_LISTA ADD CONSTRAINT POSPOSITIVA CHECK (POSICION>0);
ALTER TABLE LISTAS_LISTA ADD CONSTRAINT ANYOLISTA CHECK (ANYO>0);



/*
DROP TABLE LISTAS_PAIS CASCADE CONSTRAINTS;
DROP TABLE LISTAS_ESTADO_PROVINCIA CASCADE CONSTRAINTS;
DROP TABLE LISTAS_GENERO CASCADE CONSTRAINTS;
DROP TABLE LISTAS_CIUDAD CASCADE CONSTRAINTS;
DROP TABLE LISTAS_CANCION CASCADE CONSTRAINTS;
DROP TABLE LISTAS_LISTA CASCADE CONSTRAINTS;
DROP TABLE LISTAS_ARTISTA CASCADE CONSTRAINTS;
DROP TABLE LISTAS_GRUPO CASCADE CONSTRAINTS;
DROP TABLE LISTAS_ARTISTAIND CASCADE CONSTRAINTS;
DROP TABLE LISTAS_GENERO_CANCION CASCADE CONSTRAINTS;
DROP TABLE LISTAS_POSICION_LISTA CASCADE CONSTRAINTS;
*/

